### PR TITLE
Adding accepts header

### PR DESCRIPTION
**Pull request by yousefcisco**
This is as per Fastly's API documentation

### CODE REVIEW

**Comment by yousefcisco** [comment]
@thisandagain is there anything you'd like me to do to get this to state where it can be merged?

**Comment by thisandagain** [comment]
Looks good. I'll merge this in now.

**Comment by thisandagain** [comment]
This has been published in `fastly@2.0.0`

**Comment by yousefcisco** [comment]
Thanks!

**Pull request merged**
